// Regenerates src/server/embedded-assets.ts by inlining public/ as strings.
// Vercel's file tracer cannot see files read via Bun.file() at runtime, so
// the assets ship as source code instead — the import is what bundles them.
const files = [
  ["styles", "public/styles.css"],
  ["appJs", "public/app.js"],
  ["progressJs", "public/progress.js"],
  ["htmx", "public/vendor/htmx.min.js"],
] as const;

let out = "// Generated by scripts/embed-assets.ts — do not edit by hand.\n";
for (const [name, path] of files) {
  const text = await Bun.file(path).text();
  out += `export const ${name} = ${JSON.stringify(text)};\n`;
}
await Bun.write("src/server/embedded-assets.ts", out);
console.log("wrote src/server/embedded-assets.ts");
